/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface AppRoot {}
  interface PageAbout {}
  interface PageAboutPopover {}
  interface PageAccount {}
  interface PageLogin {}
  interface PageLogin2 {}
  interface PageMap {}
  interface PageSchedule {}
  interface PageScheduleFilter {
    'excludedTracks': string[];
  }
  interface PageSession {
    'goback': string;
    'sessionId': string;
  }
  interface PageSignup {}
  interface PageSpeakerDetail {
    'speakerId': string;
  }
  interface PageSpeakerList {}
  interface PageSupport {}
  interface PageTabs {}
  interface PageTutorial {}
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface PageAbout extends JSXBase.HTMLAttributes {}
  interface PageAboutPopover extends JSXBase.HTMLAttributes {}
  interface PageAccount extends JSXBase.HTMLAttributes {
    'onUserDidLogOut'?: (event: CustomEvent<any>) => void;
  }
  interface PageLogin extends JSXBase.HTMLAttributes {
    'onUserDidLogIn'?: (event: CustomEvent<any>) => void;
  }
  interface PageLogin2 extends JSXBase.HTMLAttributes {
    'onUserDidLogIn'?: (event: CustomEvent<any>) => void;
  }
  interface PageMap extends JSXBase.HTMLAttributes {}
  interface PageSchedule extends JSXBase.HTMLAttributes {}
  interface PageScheduleFilter extends JSXBase.HTMLAttributes {
    'excludedTracks'?: string[];
  }
  interface PageSession extends JSXBase.HTMLAttributes {
    'goback'?: string;
    'sessionId'?: string;
  }
  interface PageSignup extends JSXBase.HTMLAttributes {}
  interface PageSpeakerDetail extends JSXBase.HTMLAttributes {
    'speakerId'?: string;
  }
  interface PageSpeakerList extends JSXBase.HTMLAttributes {}
  interface PageSupport extends JSXBase.HTMLAttributes {}
  interface PageTabs extends JSXBase.HTMLAttributes {}
  interface PageTutorial extends JSXBase.HTMLAttributes {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'page-about': PageAbout;
    'page-about-popover': PageAboutPopover;
    'page-account': PageAccount;
    'page-login': PageLogin;
    'page-login2': PageLogin2;
    'page-map': PageMap;
    'page-schedule': PageSchedule;
    'page-schedule-filter': PageScheduleFilter;
    'page-session': PageSession;
    'page-signup': PageSignup;
    'page-speaker-detail': PageSpeakerDetail;
    'page-speaker-list': PageSpeakerList;
    'page-support': PageSupport;
    'page-tabs': PageTabs;
    'page-tutorial': PageTutorial;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {

  // Adding a global JSX for backcompatibility with legacy dependencies
  export namespace JSX {
    export interface Element {}
  }



  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {}
  var HTMLPageAboutElement: {
    prototype: HTMLPageAboutElement;
    new (): HTMLPageAboutElement;
  };

  interface HTMLPageAboutPopoverElement extends Components.PageAboutPopover, HTMLStencilElement {}
  var HTMLPageAboutPopoverElement: {
    prototype: HTMLPageAboutPopoverElement;
    new (): HTMLPageAboutPopoverElement;
  };

  interface HTMLPageAccountElement extends Components.PageAccount, HTMLStencilElement {}
  var HTMLPageAccountElement: {
    prototype: HTMLPageAccountElement;
    new (): HTMLPageAccountElement;
  };

  interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {}
  var HTMLPageLoginElement: {
    prototype: HTMLPageLoginElement;
    new (): HTMLPageLoginElement;
  };

  interface HTMLPageLogin2Element extends Components.PageLogin2, HTMLStencilElement {}
  var HTMLPageLogin2Element: {
    prototype: HTMLPageLogin2Element;
    new (): HTMLPageLogin2Element;
  };

  interface HTMLPageMapElement extends Components.PageMap, HTMLStencilElement {}
  var HTMLPageMapElement: {
    prototype: HTMLPageMapElement;
    new (): HTMLPageMapElement;
  };

  interface HTMLPageScheduleElement extends Components.PageSchedule, HTMLStencilElement {}
  var HTMLPageScheduleElement: {
    prototype: HTMLPageScheduleElement;
    new (): HTMLPageScheduleElement;
  };

  interface HTMLPageScheduleFilterElement extends Components.PageScheduleFilter, HTMLStencilElement {}
  var HTMLPageScheduleFilterElement: {
    prototype: HTMLPageScheduleFilterElement;
    new (): HTMLPageScheduleFilterElement;
  };

  interface HTMLPageSessionElement extends Components.PageSession, HTMLStencilElement {}
  var HTMLPageSessionElement: {
    prototype: HTMLPageSessionElement;
    new (): HTMLPageSessionElement;
  };

  interface HTMLPageSignupElement extends Components.PageSignup, HTMLStencilElement {}
  var HTMLPageSignupElement: {
    prototype: HTMLPageSignupElement;
    new (): HTMLPageSignupElement;
  };

  interface HTMLPageSpeakerDetailElement extends Components.PageSpeakerDetail, HTMLStencilElement {}
  var HTMLPageSpeakerDetailElement: {
    prototype: HTMLPageSpeakerDetailElement;
    new (): HTMLPageSpeakerDetailElement;
  };

  interface HTMLPageSpeakerListElement extends Components.PageSpeakerList, HTMLStencilElement {}
  var HTMLPageSpeakerListElement: {
    prototype: HTMLPageSpeakerListElement;
    new (): HTMLPageSpeakerListElement;
  };

  interface HTMLPageSupportElement extends Components.PageSupport, HTMLStencilElement {}
  var HTMLPageSupportElement: {
    prototype: HTMLPageSupportElement;
    new (): HTMLPageSupportElement;
  };

  interface HTMLPageTabsElement extends Components.PageTabs, HTMLStencilElement {}
  var HTMLPageTabsElement: {
    prototype: HTMLPageTabsElement;
    new (): HTMLPageTabsElement;
  };

  interface HTMLPageTutorialElement extends Components.PageTutorial, HTMLStencilElement {}
  var HTMLPageTutorialElement: {
    prototype: HTMLPageTutorialElement;
    new (): HTMLPageTutorialElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'page-about': HTMLPageAboutElement;
    'page-about-popover': HTMLPageAboutPopoverElement;
    'page-account': HTMLPageAccountElement;
    'page-login': HTMLPageLoginElement;
    'page-login2': HTMLPageLogin2Element;
    'page-map': HTMLPageMapElement;
    'page-schedule': HTMLPageScheduleElement;
    'page-schedule-filter': HTMLPageScheduleFilterElement;
    'page-session': HTMLPageSessionElement;
    'page-signup': HTMLPageSignupElement;
    'page-speaker-detail': HTMLPageSpeakerDetailElement;
    'page-speaker-list': HTMLPageSpeakerListElement;
    'page-support': HTMLPageSupportElement;
    'page-tabs': HTMLPageTabsElement;
    'page-tutorial': HTMLPageTutorialElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

